blank_issues_enabled: false
contact_links:
  - name: Discussion / Feature Request
    url: https://github.com/oRKLLM/oRKLLM/discussions
    about: For feature requests and general questions, use Discussions.
